# Generated by Django 4.0.4 on 2022-04-25 14:23

import MyOwnColumn.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('MyOwnColumn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to=MyOwnColumn.models.column_image_upload_path)),
                ('created_at', models.TimeField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='columns',
            field=models.ManyToManyField(related_name='posts', to='MyOwnColumn.column'),
        ),
        migrations.AddField(
            model_name='tag',
            name='column',
            field=models.ManyToManyField(related_name='tags', to='MyOwnColumn.column'),
        ),
    ]
