# Generated by Django 4.0.4 on 2022-04-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyOwnColumn', '0002_alter_post_user_alter_tag_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='post',
            field=models.ManyToManyField(related_name='tags', to='MyOwnColumn.post'),
        ),
    ]
